export const patients = [
  {
    idDossierMedical: 1,
    idPatient: 1,
    adresse: "Thiès",
    dateNaissance: "25-06-1990",
    email: "aissatou.fall@email.com ",
    nom: "Fall",
    prenom: "Aïssatou",
    sexe: "Femme",
    telephone: "770987654",
    password: "0000",
  },
  {
    idDossierMedical: "2",
    idPatient: "2",
    adresse: "43 Parcelles Assenies, Dakar",
    dateNaissance: "NULL",
    email: "adama.diop@email.com ",
    nom: "Diop",
    prenom: "Adama",
    sexe: "Homme",
    telephone: "NULL",
    password: "0000",
  },
  {
    idDossierMedical: "3",
    idPatient: "3",
    adresse: "12 HLM Grand Yoff, Dakar",
    dateNaissance: "NULL",
    email: "aissatou.fall@email.com ",
    nom: "Fall",
    prenom: "Aïssatou",
    sexe: "Femme",
    telephone: "NULL",
    password: "0000",
  },
  {
    idDossierMedical: "4",
    idPatient: "4",
    adresse: "23 Patte d'Oie, Dakar",
    dateNaissance: "NULL",
    email: "amadou.sow@email.com ",
    nom: "Sow ",
    prenom: "Amadou",
    sexe: "Homme",
    telephone: "NULL",
    password: "0000",
  },
  {
    idDossierMedical: "5",
    idPatient: "5",
    adresse: "8 Parcelles Assenies, Dakar",
    dateNaissance: "NULL",
    email: "aminata.ndiaye@email.com ",
    nom: "Ndiaye",
    prenom: "Aminata",
    sexe: "Femme",
    telephone: "NULL",
    password: "0000",
  },
  {
    idDossierMedical: "6",
    idPatient: "6",
    adresse: "32 Médina, Dakar",
    dateNaissance: "NULL",
    email: "assane.cisse@email.com ",
    nom: "Cissé",
    prenom: "Assane",
    sexe: "Homme",
    telephone: "NULL",
    password: "0000",
  },
  {
    idDossierMedical: "7",
    idPatient: "7",
    adresse: "15 Parcelles Assenies, Dakar",
    dateNaissance: "NULL",
    email: "binta.camara@email.com ",
    nom: "Camara",
    prenom: "Binta",
    sexe: "Femme",
    telephone: "NULL",
    password: "0000",
  },
  {
    idDossierMedical: "8",
    idPatient: "8",
    adresse: "5 Colobane, Dakar",
    dateNaissance: "NULL",
    email: "cheikh.mbengue@email.com ",
    nom: "Mbengue",
    prenom: "Cheikh",
    sexe: "Homme",
    telephone: "NULL",
    password: "0000",
  },
  {
    idDossierMedical: "9",
    idPatient: "9",
    adresse: "18 Sacré-Cœur, Dakar",
    dateNaissance: "NULL",
    email: "fatoumata.diallo@email.com ",
    nom: "Diallo",
    prenom: "Fatoumata",
    sexe: "Femme",
    telephone: "NULL",
    password: "0000",
  },
  {
    idDossierMedical: "10",
    idPatient: "10",
    adresse: "9 Liberté, Dakar",
    dateNaissance: "NULL",
    email: "idrissa.sarr@email.com ",
    nom: "Sarr",
    prenom: "Idrissa",
    sexe: "Homme",
    telephone: "NULL",
    password: "0000",
  },
  {
    idDossierMedical: "11",
    idPatient: "11",
    adresse: "27 Ouakam, Dakar",
    dateNaissance: "NULL",
    email: "khady.gueye@email.com ",
    nom: "Gueye",
    prenom: "Khady",
    sexe: "Femme",
    telephone: "NULL",
    password: "0000",
  },
  {
    idDossierMedical: "12",
    idPatient: "12",
    adresse: "10 Parcelles Assenies, Dakar",
    dateNaissance: "NULL",
    email: "mamadou.ba@email.com ",
    nom: "Ba",
    prenom: "Mamadou",
    sexe: "Homme",
    telephone: "NULL",
    password: "0000",
  },
  {
    idDossierMedical: "13",
    idPatient: "13",
    adresse: "14 Gueule Tapée, Dakar",
    dateNaissance: "NULL",
    email: "mariama.ndao@email.com ",
    nom: "Ndao",
    prenom: "Mariama",
    sexe: "Femme",
    telephone: "NULL",
    password: "0000",
  },
  {
    idDossierMedical: "14",
    idPatient: "14",
    adresse: "3 Parcelles Assenies, Dakar",
    dateNaissance: "NULL",
    email: "mohamed.fall@email.com ",
    nom: "Fall",
    prenom: "Mohamed",
    sexe: "Homme",
    telephone: "NULL",
    password: "0000",
  },
  {
    idDossierMedical: "15",
    idPatient: "15",
    adresse: "22 Grand Dakar, Dakar",
    dateNaissance: "NULL",
    email: "nafissatou.dieng@email.com ",
    nom: "Dieng",
    prenom: "Nafissatou",
    sexe: "Femme",
    telephone: "NULL",
    password: "0000",
  },
  {
    idDossierMedical: "16",
    idPatient: "16",
    adresse: "7 Parcelles Assenies, Dakar",
    dateNaissance: "NULL",
    email: "ousmane.mbaye@email.com ",
    nom: "Mbaye",
    prenom: "Ousmane",
    sexe: "Homme",
    telephone: "NULL",
    password: "0000",
  },
  {
    idDossierMedical: "17",
    idPatient: "17",
    adresse: "31 Mermoz, Dakar",
    dateNaissance: "NULL",
    email: "rokhaya.gomis@email.com ",
    nom: "Gomis",
    prenom: "Rokhaya",
    sexe: "Femme",
    telephone: "NULL",
    password: "0000",
  },
  {
    idDossierMedical: "18",
    idPatient: "18",
    adresse: "645 Usines Niary Tally",
    dateNaissance: "2024-01-20",
    email: "neufdione@gmail.com ",
    nom: "Dione",
    prenom: "Papa Adiouma",
    sexe: "Homme",
    telephone: "779156318",
  },
];
